sonar.projectKey=hgvdesk-platform_hgvdesk-platform
sonar.organization=hgvdesk-platform
sonar.projectName=HGVDesk Platform

sonar.sources=server,frontend
sonar.exclusions=**/node_modules/**,**/*.min.js,server/.puppeteer-cache/**,frontend/images/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
